version: '3.0'

services:
  mongodb:
    container_name: mongodb
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local